import type { DealForMe } from "./types"

export const MOCK_DEALS_FOR_ME: DealForMe[] = [
  {
    id: "1",
    name: "TechCorp AI",
    tagline: "AI-powered financial document analysis",
    matchPct: 94,
    variant: "excellent",
    sector: "Fintech",
    stage: "Series A",
    location: "Bangalore",
    age: "18 months old",
    metrics: [
      { label: "ARR", value: "₹12 Cr (180% YoY)" },
      { label: "Customers", value: "45 enterprises" },
      { label: "Team", value: "22 (ex-Google, ex-Flipkart)" },
    ],
    raising: "Raising ₹25 Cr",
    valuation: "₹300 Cr",
    minTicket: "Min ticket: ₹25 Lakhs",
    closing: "Closing: Feb 15 (18 days left)",
    aiSays:
      "Strong product-market fit, excellent team background, matches your fintech + AI preference",
    alsoInterested: "Vikram M., Anita D. + 3 angels",
  },
  {
    id: "2",
    name: "GreenLeaf Energy",
    tagline: "Sustainable energy for enterprises",
    matchPct: 87,
    variant: "syndicate",
    sector: "CleanTech",
    stage: "Seed",
    location: "Mumbai",
    age: "12 months old",
    metrics: [
      { label: "MRR", value: "₹25 Lakhs (15% MoM)" },
      { label: "Pilot customers", value: "8 enterprises" },
      { label: "Team", value: "12 (domain experts)" },
    ],
    raising: "Raising ₹8 Cr",
    valuation: "₹40 Cr",
    minTicket: "Syndicate min: ₹5 Lakhs (via Rajan's Fund)",
    closing: "Closing: Feb 8 (11 days left)",
    aiSays:
      "High-growth sector, but outside your typical focus. Consider for portfolio diversification.",
    syndicateLabel: "Syndicate",
  },
  {
    id: "3",
    name: "EduLearn Pro",
    tagline: "B2B SaaS for corporate training",
    matchPct: 72,
    variant: "lower",
    sector: "EdTech",
    stage: "Pre-Seed",
    location: "Delhi",
    age: "8 months old",
    metrics: [
      { label: "Revenue", value: "₹8 Lakhs MRR" },
      { label: "Customers", value: "15 SMBs" },
      { label: "Team", value: "6 (first-time founders)" },
    ],
    raising: "Raising ₹3 Cr",
    valuation: "₹15 Cr",
    minTicket: "Min ticket: ₹10 Lakhs",
    aiConcerns: [
      "First-time founders (higher risk)",
      "EdTech outside your typical focus",
      "Valuation seems high for current traction",
    ],
  },
]
